export const DEFAULT_TRANSACTION_SETTINGS = {
  autoCloseTableAfterPay: false,
  autoCloseDeliveredTableFromKitchen: false,
  autoClosePacketAfterPay: false,
  // null = all methods, [] = none, ["cash", ...] = subset
  autoClosePacketAfterPayMethods: null,
  autoNavigateTableAfterConfirm: false,
  presetNotes: ["No ketchup", "Extra spicy", "Sauce on side", "Well done"],
  disableAutoPrintTable: false,
  disableAutoPrintPacket: false,
  disableTableOverviewOrdersFloatingButton: false,
  disableTableOverviewGuestsFloatingButton: false,
  disableTableOverviewSongRequestFooterButton: false,
  requireGuestsBeforeOpen: true,
  enableManualTableLock: true,
  enableProductGridVirtualization: false,
  enableCartVirtualization: false,
  virtualizationProductOverscan: 6,
  virtualizationCartOverscan: 8,
};
